In [2]:
import numpy as np
import pandas as pd

# Day=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
outlook = np.array(['Sunny', 'Sunny', 'Overcast', 'Rain', 'Rain', 'Rain', 'Overcast', 
                    'Sunny', 'Sunny', 'Rain', 'Sunny', 'Overcast', 'Overcast', 'Rain'])

temperature = np.array(["Hot", "Hot", "Hot", "Mild", "Cool", "Cool", "Cool", 
                       "Mild", "Cool", "Mild", "Mild", "Mild", "Hot", "Mild"])

humidity = np.array(["High", "High", "High", "High", "Normal", "Normal", "Normal", 
                     "High", "Normal", "Normal", "Normal", "High", "Normal", "High"])

wind = np.array(["Weak", "Strong", "Weak", "Weak", "Weak", "Strong", "Strong", 
                 "Weak", "Weak", "Weak", "Strong", "Strong", "Weak", "Strong"])

play = np.array(["No", "No", "Yes", "Yes", "Yes", "No", "Yes", 
                 "No", "Yes", "Yes", "Yes", "Yes", "Yes", "No"])



In [3]:
#Encoding

from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
outlook_encoder=lab.fit_transform(outlook)
outlook_encoder


array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [4]:
temperature_encoder=lab.fit_transform(temperature)
temperature_encoder

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

In [5]:
humidity_encoder=lab.fit_transform(humidity)
humidity_encoder

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0])

In [6]:
wind_encoder=lab.fit_transform(wind)
wind_encoder

array([1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0])

In [7]:
feature=list(zip(outlook_encoder,temperature_encoder,humidity_encoder,wind_encoder))
feature

[(np.int64(2), np.int64(1), np.int64(0), np.int64(1)),
 (np.int64(2), np.int64(1), np.int64(0), np.int64(0)),
 (np.int64(0), np.int64(1), np.int64(0), np.int64(1)),
 (np.int64(1), np.int64(2), np.int64(0), np.int64(1)),
 (np.int64(1), np.int64(0), np.int64(1), np.int64(1)),
 (np.int64(1), np.int64(0), np.int64(1), np.int64(0)),
 (np.int64(0), np.int64(0), np.int64(1), np.int64(0)),
 (np.int64(2), np.int64(2), np.int64(0), np.int64(1)),
 (np.int64(2), np.int64(0), np.int64(1), np.int64(1)),
 (np.int64(1), np.int64(2), np.int64(1), np.int64(1)),
 (np.int64(2), np.int64(2), np.int64(1), np.int64(0)),
 (np.int64(0), np.int64(2), np.int64(0), np.int64(0)),
 (np.int64(0), np.int64(1), np.int64(1), np.int64(1)),
 (np.int64(1), np.int64(2), np.int64(0), np.int64(0))]

In [9]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(feature,play)
print(model.predict([[2, 0, 0, 0]]))


['No']
